### ISSUE TITLE
jsonld-java-rdf2go not released in maven central

### ISSUE THREAD

**Issue by ismriv** [jsonld-java/jsonld-java#106]
I was trying to use this integration module in a project, but it doesn't seem to have been released to maven central: http://mvnrepository.com/artifact/com.github.jsonld-java

Is there any issue with it or something I can help with?

**Comment by stuehmer** [comment]
FYI, I moved Semweb4j (RDF2Go and RDFReactor) to Github before the shutdown of GoogleCode. See: @semweb4j https://github.com/semweb4j/semweb4j
