### ISSUE TITLE
Specifying multiple types for a node

### ISSUE THREAD

**Issue by mbellani360** [jsonld-java/jsonld-java#112]
Hello, 

Per the spec here, looks like array types should be supported as in:
EXAMPLE 13: Specifying multiple types for a node
{
...
  "@id": "http://example.org/places#BrewEats",
  "@type": [ "http://schema.org/Restaurant", "http://schema.org/Brewery" ],
...
}

I tried to construct a jackson ObjectNode and filled  with an ArrayNode and it failed, looks like it's not supported yet. 

        if (val.containsKey("@type")) {
            if (!(val.get("@type") instanceof String)) {
                throw new JsonLdError(Error.INVALID_TYPE_MAPPING, val.get("@type"));
            }

Is this feature planned or am i doing something wrong? 

Thanks
Manish

**Comment by ansell** [comment]
Needs further detail from user, open if still an issue and you have a minimal test case.
