### ISSUE TITLE
Cannot compact to a single string valued context

### ISSUE THREAD

**Issue by jeff303** [jsonld-java/jsonld-java#138]
Observe the following JSON-LD compaction

http://tinyurl.com/lombs75

Notice that the final `@context` in the output document is simply "http://schema.org", a String value.  There seems to be no way to attain this output through JSON-LD.  When taking the same JSON and new context as shown in the paste, the output from jsonld-java (version 0.51) is `"@context" : [ "http://schema.org" ]`.  Is this a known issue, or are there any other workarounds short of stripping out the context entirely and adding it manually to the resulting map?  Thanks.

**Comment by ansell** [comment]
Could you post the steps that you are going through to get the context with that array?

The likely candidate is that compactArrays is set to false, but I don't know what code path you are using right now.

**Comment by jeff303** [comment]
Here is a quick test case.

	@Test
	public void testCompaction() throws JsonLdError, JsonGenerationException, IOException {
				
		final Map<String, Object> contextAbbrevs = new HashMap<>();
		contextAbbrevs.put("so", "http://schema.org/");

		final Map<String, Object> json = new HashMap<>();
		json.put("@context", contextAbbrevs);
		json.put("@id", "http://example.org/my_work");

		final List<Object> types = new LinkedList<>();
		types.add("so:CreativeWork");

		json.put("@type", types);
		json.put("so:name", "My Work");
		json.put("so:url", "http://example.org/my_work");

		final JsonLdOptions options = new JsonLdOptions();
		options.setBase("http://schema.org/");
		options.setCompactArrays(true);

		System.out.println("Before compact");
		System.out.println(JsonUtils.toPrettyString(json));
		
		final List<String> newContexts = new LinkedList<>();
		newContexts.add("http://schema.org/");
		final Map<String, Object> compacted = JsonLdProcessor.compact(json, newContexts, options);

		System.out.println("\n\nAfter compact:");
		System.out.println(JsonUtils.toPrettyString(compacted));
	}

Here is the output.  The compactArrays is clearly doing something because it eliminates the `@type` value array in the output.  It just doesn't seem to be applying to `@context`.

```
Before compact
{
  "@context" : {
    "so" : "http://schema.org/"
  },
  "@type" : [ "so:CreativeWork" ],
  "so:url" : "http://example.org/my_work",
  "so:name" : "My Work",
  "@id" : "http://example.org/my_work"
}


After compact:
{
  "@id" : "http://example.org/my_work",
  "@type" : "CreativeWork",
  "name" : "My Work",
  "http://schema.org/url" : "http://example.org/my_work",
  "@context" : [ "http://schema.org/" ]
}
```

**Comment by ansell** [comment]
Thanks for the test case. I will look through it and see if there is a bug in that code path.

**Comment by jeff303** [comment]
Thanks!  The only reason this even matters is because Gmail is so picky about what it recognizes w.r.t. JSON-LD.  Even though they are effectively the same in this case, Gmail only recognizes documents with `"@context" : "http://schema.org"`.

**Comment by ansell** [comment]
The place where the list is being created is based on point 2 of the context processing algorithm:

http://www.w3.org/TR/json-ld-api/#context-processing-algorithm

I can't find any place after that in the compaction algorithm where it says to reduce the list back to a scalar if it has only one element. The reduction rules only seem to apply to the elements outside of the context, in point 2.3 of:

http://www.w3.org/TR/json-ld-api/#compaction-algorithm

The context is only added after the formal steps, based on the text just after point 8 of the compaction algorithm.

It isn't clear that what the exact meaning of "Finally, if a non-empty context has been passed, add an @context member to result and set its value to the passed context." is in relation to the compaction algorithm itself.

I will look into this a little more, but given that the text is a little vague, I may simply be able to reduce single element vector contexts to scalars without violating any of the spec, as it appears jsonld.js does.

**Comment by ansell** [comment]
Could you test with the latest 0.6.0-SNAPSHOT from Sonatype Snapshots repository (or compile from Git) to verify that it fixes your issue?

**Comment by jeff303** [comment]
@ansell , this works great.  Thanks for the extremely fast turnaround!
