### ISSUE TITLE
URL are not expanded

### ISSUE THREAD

**Issue by redskate** [jsonld-java/jsonld-java#142]
Hi :)

I tryied to expand a small example including a context and a graph. See below. While the Playground expands it perfectly, JSONLD-Java don't ! 

Why?

The Code:
                Object jsonLDObject = JsonUtils.fromInputStream(new FileInputStream(F));
		@SuppressWarnings("rawtypes")
		Map context = new HashMap();
		JsonLdOptions options = new JsonLdOptions();

		PrintStream json_out = new PrintStream(new File(compactedjsonfile));
		JsonLdProcessor.compact(jsonLDObject, context, options);
		json_out.println( JsonUtils.toPrettyString(jsonLDObject) );
		System.out.println("Find compacted JSON file under "+compactedjsonfile);
	
		
		json_out = new PrintStream(new File(expandedjsonfile));
		JsonLdProcessor.expand(jsonLDObject, options);
		json_out.println( JsonUtils.toPrettyString(jsonLDObject) );
		System.out.println("Find expanded JSON file under "+expandedjsonfile);
	
		
		json_out = new PrintStream(new File(flattenedjsonfile));
		JsonLdProcessor.flatten(jsonLDObject, options);
		json_out.println( JsonUtils.toPrettyString(jsonLDObject) );
		System.out.println("Find flattened JSON file under "+flattenedjsonfile);

The data
I will send you the data per email, since it is not free....

Thanks
Fabio

**Comment by redskate** [comment]
Must have been a cache problem. Now it is running. Thanks!

**Comment by redskate** [comment]
Sorry, I have to reopen it.
The code definitely does not substitute urls....

Why? Any hint will be appreciated

**Comment by ansell** [comment]
Can you anonymise or obfuscate the data and post it here. Unfortunately, I can't help without more details.
