### ISSUE TITLE
Trailing non-whitespace does not cause a parse error.

### ISSUE THREAD

**Issue by afs** [jsonld-java/jsonld-java#144]
Example: 
```
{
  "@id" : "http://example/s",
  "http://example/p" : "str"
}
xxxxxxxxxxxxxxx
```
This does not cause a parse error (insert debate about whether it should or not).

When getting the JSON object to process there are two calls:

`JsonUtils.fromInputStream` : this wraps the input stream in a BufferedReader so the caller can't check the stream on return because the stream has been read ahead.

`JsonUtils.fromReader`: Jackson seems to read to the end of top-level object "}" but it also consumes the reader because Jackson does it's own internal buffering in `ReaderBasedJsonParser.loadMore`.

This all makes the issue, in a practical way, impossible to fix in code calling jsonld-java.  The only way I can see is for `JsonUtilsfromReader` to look at the `JsonParser` it creates.

I'll investigate further - this issue is to log the issue.

I used version 0.5.1 -- the code in JsonUtils in HEAD is the same.

**Comment by ansell** [comment]
Trailing non-whitespace should definitely create a parse error, as it is not a valid JSON document in that case... right??? I will look into this again later in the week and release a new version after it is fixed.

**Comment by afs** [comment]
I think so. The relevant spec text is:

http://www.w3.org/TR/json-ld/#json-ld-grammar

> A JSON-LD document MUST be a valid JSON document as described in [RFC4627].
> 
> A JSON-LD document MUST be a single node object or an array whose elements are each node objects at the top level.

but the definition of "JSON document" is descriptive and does not say clearly that I can see that no junk afterwards is illegal. The test question is whether the JSON Document ended at the top-level "}" or is it the whole input?  I'll ask on the list.
