### ISSUE TITLE
abbreviation should use longest possible prefix (Jena RIOT)

### ISSUE THREAD

**Issue by VladimirAlexiev** [jsonld-java/jsonld-java#153]
Look at the files in #152. They define prefixes like this (and many similar pairs):
```
    "aat" : "http://vocab.getty.edu/aat/",
    "aat_rev" : "http://vocab.getty.edu/aat/rev/",
```
Inside the jsonld, the following cURI is emitted:
* `"aat:rev/5003693123"`
I think it should use the longer prefix and should be:
* `"aat_rev:5003693123"`

In this case there isn't much of a difference, but consider eg dbr: vs dbc: http://prefix.cc/dbc,dbr.file.jsonld
```js
    "@context": {
        "dbc": "http://dbpedia.org/resource/Category:",
        "dbr": "http://dbpedia.org/resource/"
    }
```

**Comment by ansell** [comment]
I will look into how the determination of the prefix to use is done.

**Comment by ansell** [comment]
The algorithm where the longest prefix should be calculated is at:

http://www.w3.org/TR/json-ld-api/#iri-compaction

The implementation of 5.4 seems to be the key for this issue, and it is a horribly complex statement right now that may need some further testing past the base testsuite to make sure it handles all of the corner cases.

Right now it is implemented as:

                // 5.3)
            final String candidate = term + ":"
                    + iri.substring(((String) termDefinition.get("@id")).length());
            // 5.4)
            if ((compactIRI == null || compareShortestLeast(candidate, compactIRI) < 0)
                    && (!termDefinitions.containsKey(candidate) || (iri
                            .equals(((Map<String, Object>) termDefinitions.get(candidate))
                                    .get("@id")) && value == null))) {
                compactIRI = candidate;
            }

**Comment by ansell** [comment]
One cause seems to be that the values passed to JsonLdUtils.compareShortestLeast are the following, which are of identical length. Ie, the prefix IRIs are not being passed in, and it is checking lexically on the result of prefixing the term to pick the shortest one, and in this case then using Integer.signum(a.compareTo(b)) as the return value:

    aat_rev:5001065997
    aat:rev/5001065997

**Comment by ansell** [comment]
I am going to close this as won't fix, as it appears that we have the correct behaviour based on the spec.

Specifically, 5.4 in the spec says the following:
    If either compact IRI is null or candidate is shorter or the same length but lexicographically less than compact IRI and candidate does not have a term definition in active context or if the term definition has an IRI mapping that equals iri and value is null, set compact IRI to candidate.

It is optimising for the length of the final string, rather than the length of the prefix.

A workaround may be to rename the namespace so that it is shorter than the parts of the URI that it is replacing. Ie, use aatrev, which would be one character shorter, and then would be selected by that algorithm.

**Comment by gkellogg** [comment]
That is what the spec says, but it often gives undesirable results when you have term definitions that you wouldn't want to use as prefixes. My Ruby implementation favors using terms with a string value over those with an object value. It's apiece opal, but more satisfying. That way if you define "schema": "http://schema.org/" and "item": {"@id": "schema:item"} "http://schema.org/itemList" is compacted to "schema:itemList" and not "item:List".

**Comment by VladimirAlexiev** [comment]
@ansell could you please add a test for this:
```
        "dbc": "http://dbpedia.org/resource/Category:",
        "dbr": "http://dbpedia.org/resource/"
```
And then
```
dbc:Food_and_drink
dbr:Food
```

@gkellogg very good example!  A prefix should work on punctuation, not in the middle of a word :-(

**Comment by ansell** [comment]
Thinking about this again last night, there are other approaches that we can do without heavily modifying the semantics of step 5.4. In particular, when the lengths are the same, it may be useful to add a check to determine the largest prefix before going to the full lexicographical step. That would technically be a violation of the spec, but I think that people would prefer something more "common-sense" in the case of a length tie, before going to the lexicographical comparison that isn't really common-sense IMO.

I will look into how the test of the dbpedia URIs go today to see whether the addition of a prefix length check would be valuable.

**Comment by ansell** [comment]
The output for the DBPedia URIs is as expected, but I am looking into another minor issue with the namespaces that are populated into RDFDataset, as dbc is missing in a related test there.

    {
      "@id" : "dbr:Food",
      "@type" : "dbc:Food_and_drink",
       "@context" : {
        "dbr" : "http://dbpedia.org/resource/",
        "dbc" : "http://dbpedia.org/resource/Category:"
      }
    }

**Comment by ansell** [comment]
Closing as the main issue here is fixed.
