### ISSUE TITLE
Missing artifact com.github.jsonld-java:jsonld-java:jar:0.7.1-SNAPSHOT

### ISSUE THREAD

**Issue by luispcosta** [jsonld-java/jsonld-java#155]
Hello. I'm trying to include json-ld into my maven configuration file and for some reason I just can't get it to work. I've included the dependency on the `pom.xml` as specified in the [readme file](https://github.com/jsonld-java/jsonld-java/blob/master/README.md) file:

```xml
<dependency>
    <groupId>com.github.jsonld-java</groupId>
    <artifactId>jsonld-java</artifactId>
    <version>0.7.1-SNAPSHOT</version>
</dependency>
```

And I always get the error:

`Missing artifact com.github.jsonld-java:jsonld-java:jar:0.7.1-SNAPSHOT`

I've tried right clicking the project, going to `Maven -> Update Project` (with the option **Force updated of Snapshots/Releases**) and rebuilding the project. 

How can I solve this?

I can provide more details about the project and the pom.xml file but I don't think the problem lies there, does it?

**Comment by ansell** [comment]
Sorry for that confusing reference. I will change it to reference the latest release, which right now is 0.7.0.
