### ISSUE TITLE
Support Android with gradle build

### ISSUE THREAD

**Issue by ghost** [jsonld-java/jsonld-java#169]
It would be great if `jsonld-java` can compatible with Android.

I resolved following compile errors:
##### 2. Imports jackson in `build.gradle` to fix missing `com.fasterxml.jackson.*`

```
compile 'com.fasterxml.jackson.datatype:jackson-datatype-json-org:2.7.3'
compile 'com.fasterxml.jackson:jackson-parent:2.7-1'
```

**Comment by ansell** [comment]
I haven't looked into it for a while but last time I looked the use of Apache Commons HTTPClient 4.4/4.5 was a blocker for android as Google have included an ancient version of HTTPClient statically in Android that cannot be updated or substituted.

We also do not use gradle right now.

**Comment by ansell** [comment]
If you want to support Android it would need to be done in a separate module, implementing the DocumentLoader interface using your preferred libraries. Closing this based on lack of feedback. Reopen if you still plan on creating an Android compatible module.
