### ISSUE TITLE
keys: long or short, it depends on the values of the property (uri or string). Why?

### ISSUE THREAD

**Issue by fpservant** [jsonld-java/jsonld-java#170]
Hi,

Writing out jena models in JSON-LD, why is it that the keys corresponding to properties whose values are strings are handled differently than the keys whose values are URIs?

(not sure whether this is for jsonld-java or jena - please excuse me if I am sending this to the wrong place)

For instance, with following RDF:
<http://www.a.com/foo/s> <http://www.a.com/foo/p>  <http://www.a.com/foo/o> .

we get:
```
{
  "@id" : "http://www.a.com/foo/s",
  "p" : "http://www.a.com/foo/o",
  "@context" : {
    "p" : {
      "@id" : "http://www.a.com/foo/p",
      "@type" : "@id"
    }
  }
}

```
note that the key for the property is "p" - nice.

But for:
`<http://www.a.com/foo/s> <http://www.a.com/foo/p>  "a string" .
`
we get:
```
{
  "@id" : "http://www.a.com/foo/s",
  "http://www.a.com/foo/p" : {
    "@language" : "fr",
    "@value" : "a string"
  },
  "@context" : {
    "p" : {
      "@id" : "http://www.a.com/foo/p",
      "@type" : "http://www.w3.org/1999/02/22-rdf-syntax-ns#langString"
    }
  }
}

```
Note that here, the key is "http://www.a.com/foo/p". Why not just "p"?

TIA
Best Regards,
fps

**Comment by fpservant** [comment]
The trouble comes from the line `"@type" : "http://www.w3.org/1999/02/22-rdf-syntax-ns#langString"`in the context, which is computed by jena.
Jsonld-java is right in his behavior, [cf.](https://lists.w3.org/Archives/Public/public-linked-json/2016Apr/0006.html)

**Comment by afs** [comment]
This is a RDF 1.1 ism. 

Now that literals with a language also have a type of rdf:langString, then the output processor should ignore the type if a langTag is p[resent. That is, to be safe for RDF 1.0 and RDF 1.1

    if hasLang ... 
    else if hasType ... 
    else ...

There is a similar situation with xsd:string which can be omitted for RDF 1.1 (and it is preferred to omit it).

A quick scan of the JSON-LD spec suggests the algorithms in the spec do sometimes have this the wrong way round :`@type` case before `@language`.
