### ISSUE TITLE
Different result from JSONLD-JAVA and Playground

### ISSUE THREAD

**Issue by mmazurkevich** [jsonld-java/jsonld-java#174]
Was found unexpected behavior JSONLD-JAVA. There was a different result from playground and current version of library, using JSON-LD Frame. All files for test attached  in gist. 
https://gist.github.com/mmazurkevich/46d4018ec5d8419a5f55fe2739fdf591
- source.jsonsource expanded json document
- frame.json - frame document
- jsonld-tools-exec.sh - how JSONLD-java transformation is called to provide transformation
- result.json - what do you get form JSONLD-java transformations
- expected_result.json - what should actually get from playground.

`--context frame.json --format jsonld --inputFile source.json --outputForm compacted --process frame   (parameters for execution)`
Unexpected `@list` mapping started from fourth JSON object. `@list` consist of id: but do not has embeded object. After some small analyses i found point, after which object is different.This point is in JsonLdApi class in generateNodeMap method.
May be any advice how to solve the problem or where may be the problem?

**Comment by ansell** [comment]
The document you provided for testing is quite large and difficult to verify. Could you reduce it to the smallest document that still shows the bug you are seeing?

**Comment by mmazurkevich** [comment]
Hello, @ansell 
I tried to reproduce this bug with more easy JSON, files are attached. They have same value like before. And it is the simplest JSON, which i can think of. In this example, list does not have field `type`  of previous object.  I think, that method `generateNodeMap` does not add object with same id to `list`.
https://gist.github.com/mmazurkevich/15b7b3456878d53913f92068e70c591b

**Comment by ansell** [comment]
I have compiled your test case into a regression test on a branch but I don't yet understand what is triggering it so it isn't fixed at this point. The branch is at:

https://github.com/jsonld-java/jsonld-java/compare/github-174-framing?expand=1
