### ISSUE TITLE
@base ignored in embedded context when remote context is included

### ISSUE THREAD

**Issue by balhoff** [jsonld-java/jsonld-java#175]
For this document and jsonld-java 0.8.2:

``` json
{
    "@context": [ 
"https://raw.githubusercontent.com/monarch-initiative/monarch-app/master/conf/monarch-context.jsonld",
        {
            "@base": "http://example.org/base/",
            "ex": "http://example.org/",
            "ex:friendOf": {
                "@type": "@id"
            }
        }
    ],
    "@id": "3456",
    "ex:name": "Jim",
    "ex:friendOf": "1234",
    "@type": "Person"
}
```

The value of `@base` is not used when calling `JsonLdProcessor.expand()`. I get this result:

``` json
[ {
  "@id" : "3456",
  "@type" : [ "Person" ],
  "http://example.org/friendOf" : [ {
    "@id" : "1234"
  } ],
  "http://example.org/name" : [ {
    "@value" : "Jim"
  } ]
} ]
```

If I remove the reference to the external context to create this document:

``` json
{
    "@context": [ 
        {
            "@base": "http://example.org/base/",
            "ex": "http://example.org/",
            "ex:friendOf": {
                "@type": "@id"
            }
        }
    ],
    "@id": "3456",
    "ex:name": "Jim",
    "ex:friendOf": "1234",
    "@type": "Person"
}
```

the `@base` is used to expand IRIs like `http://example.org/base/1234`:

``` json
[ {
  "@id" : "http://example.org/base/3456",
  "@type" : [ "http://example.org/base/Person" ],
  "http://example.org/friendOf" : [ {
    "@id" : "http://example.org/base/1234"
  } ],
  "http://example.org/name" : [ {
    "@value" : "Jim"
  } ]
} ]
```

Is this expected behavior? This is not the behavior of JSON-LD Playground, which does use the `@base` from the embedded context when used with a remote context (I posted a [question to the JSON-LD mailing list](https://lists.w3.org/Archives/Public/public-linked-json/2016May/0002.html) but haven't gotten an answer there). JSON-LD Playground will even make use of `@base` in a remote context, which seems to be disallowed by the [spec](http://www.w3.org/TR/json-ld/): "Please note that the @base will be ignored if used in external contexts."

**Comment by ansell** [comment]
The reasoning in step 3.4 of the JSONLD-API Expansion algorithm looks to have some logic issues that have been translated into the implementation here.

https://www.w3.org/TR/json-ld-api/#context-processing-algorithm

Specifically, the following sentence doesn't seem to work with mixed contexts such as you have:

    "If context has an @base key and remote contexts is empty, i.e., the currently being processed context is not a remote context: "

It should actually be deciding based on whether the current context being processed is the local context or one of the remote contexts, rather than assuming mixed contexts will not occur.

I will work on fixing the logic that we are implementing there. It may be tricky as the implementation is recursive right now, so it is calling the same method for the remote contexts and I will need to figure out how to track if that is happening and specifically avoid setting @base if it does.

**Comment by ansell** [comment]
One workaround I discovered while tweaking is that you can swap the order of the remote and local contexts and it will parse as expected. Ie, put the monarch URL after the local context.

There is some corruption when it processes the remote context first with it setting "@base" internally to the empty string "" which also needs to be worked through as part of this issue.

**Comment by ansell** [comment]
Fixed by pull request #176

**Comment by balhoff** [comment]
Thanks @ansell!

**Comment by ansell** [comment]
Released jsonld-java-0.8.3 with this fix in it, should be on Maven Central in a few hours

**Comment by dr0i** [comment]
@balhoff any chance to get the `monarch-context.jsonld` ? The URL doesn't exist anymore and tests are failing. I would copy it into this repo.

**Comment by balhoff** [comment]
@dr0i it seems there have been a lot of changes in that repository. Can you try using this file for the test? https://github.com/prefixcommons/biocontext/blob/master/registry/monarch_context.jsonld

**Comment by balhoff** [comment]
@dr0i here is where the old repo moved: https://github.com/monarch-initiative/monarch-legacy/blob/master/conf/monarch-context.jsonld

**Comment by dr0i** [comment]
Thx @balhoff ! Will look into that.

**Comment by dr0i** [comment]
Thx again - I've put the context into this repo so that tests are unlikely to brake.
