### ISSUE TITLE
NullPointerException in JsonLdApi.removeDependents

### ISSUE THREAD

**Issue by KMax** [jsonld-java/jsonld-java#179]
Unfortunately, I can only provide a stacktrace. I tried to prepare a unit test, but I've not succeed yet, because the exception is thrown occasionally.

```
java.lang.NullPointerException
	at com.github.jsonldjava.core.JsonLdApi.removeDependents(JsonLdApi.java:1575)
	at com.github.jsonldjava.core.JsonLdApi.removeEmbed(JsonLdApi.java:1568)
	at com.github.jsonldjava.core.JsonLdApi.frame(JsonLdApi.java:1390)
	at com.github.jsonldjava.core.JsonLdApi.frame(JsonLdApi.java:1466)
	at com.github.jsonldjava.core.JsonLdApi.frame(JsonLdApi.java:1311)
	at com.github.jsonldjava.core.JsonLdProcessor.frame(JsonLdProcessor.java:306)
```

At this line of code:
```
final Object p = e.parent != null ? e.parent : newMap();
```
I guess the variable `e` may be `null` sometimes.

- I run `JsonLdProcessor.frame(...)` with the default `JsonLdOptions` (without arguments, i.e. `new JsonLdOptions()`).
- Faced the issue with 0.8.3 version of the library.

**Comment by KMax** [comment]
Can 
```
final Object p = (e != null && e.parent != null) ? e.parent : newMap();
```
be a solution? I run all the tests with this change and all of them passed :) But I don't understand the logic of the algorithm, so it's hard to me to conclude that this change is a solution.

**Comment by ansell** [comment]
I haven't seen this stack trace myself before, but more sanity checks are unlikely to change the conformance with the spec algorithm. Will look into this.

**Comment by ansell** [comment]
Fixed this by modifying the loop a little. Should also have a slight performance advantage in that it won't create a loop local map just to do a get on a key that doesn't exist on it and check that it matches a non-null key, which it won't and hence won't have side effects after that point.

Fix is deployed to the sonatype snapshots repository as 0.8.4-SNAPSHOT. Won't do another release today just for this given 0.8.3 just came out 48 hours ago, but may do one in the next week or two with this in it.
