### ISSUE TITLE
JsonLdOptions aren't used for compaction in framing

### ISSUE THREAD

**Issue by jindrichmynarz** [jsonld-java/jsonld-java#182]
`JsonLdOptions` are only used for expanding input and frame in JSON-LD framing. When the framed result is compacted, `JsonLdOptions` are ignored and [set to `null`](https://github.com/jsonld-java/jsonld-java/blob/master/core/src/main/java/com/github/jsonldjava/core/JsonLdProcessor.java#L315). When I read the [JSON-LD Framing algorithm](http://json-ld.org/spec/latest/json-ld-framing/#framing-algorithm), I can't find any instruction to ignore the `JsonLdOptions` in compaction.

**Comment by ansell** [comment]
Could you attach a short test with the methods and sequence that you are using so I can work through replicating it?

**Comment by jindrichmynarz** [comment]
JSON-LD:

```json
{
  "@context": {
    "@vocab": "http://xmlns.com/foaf/0.1/",
    "member": {"@type": "@id"}
  },
  "@graph": [{
    "@type": "Person",
    "member": "_:b1"
  }, {
    "@id": "_:b1",
    "@type": "Group"
  }]
}
```

Frame:

```json
{
  "@context": {
    "@vocab": "http://xmlns.com/foaf/0.1/"
  },
  "@type": "Person"
}
```

JSON-LD options with `setCompactArrays` set to `false`:

```java
final JsonLdOptions options = new JsonLdOptions();
options.setCompactArrays(false);
```

Result of `JsonLdProcessor.frame(jsonld, frame, options);`

```
{
  "@context" : {
    "@vocab" : "http://xmlns.com/foaf/0.1/"
  },
  "@graph" : [ {
    "@id" : "_:b0",
    "@type" : "Person",
    "member" : {
      "@id" : "_:b1",
      "@type" : "Group"
    }
  } ]
}
```

Notice that the object of `foaf:member` is not wrapped in an array.

Expected result:

```
{
  "@context" : {
    "@vocab" : "http://xmlns.com/foaf/0.1/"
  },
  "@graph" : [ {
    "@id" : "_:b0",
    "@type" : "Person",
    "member" : [{
      "@id" : "_:b1",
      "@type" : "Group"
    }]
  } ]
}
```

The expected result can be also obtained by compacting the result of framing.

As I indicated above, framing compacts its result with `null` options, so the provided options are ignored and instead the default options are applied.

**Comment by ansell** [comment]
This should be fixed by pull request #183 and be in the next release, which should be 0.9.0.

**Comment by jindrichmynarz** [comment]
I think this only solves the specific example of array compaction. Why not pass the whole JSON-LD options given to framing to compaction?

**Comment by ansell** [comment]
It should already have access to those as part of being an instance of JsonLdApi with the options passed to its constructor. The call to compact that allows the compactArrays preference to be overridden is a slightly strange case and I am not sure why it is there exactly but this seems to work around it by passing it through.
