### ISSUE TITLE
Does loading the context from classpath actually work?

### ISSUE THREAD

**Issue by digitalheir** [jsonld-java/jsonld-java#185]
I'm trying to load a JSON-LD document with an offline context. But the document loader does not seem to short circuit the remote URI to the local one, even though it seems to me that it is in the class path. I can also not find the source code where this is supposed to happen. Using library version 0.8.3 through Maven. See source code:

``` java
class Tests {
    static String convertStreamToString(java.io.InputStream is) {
        java.util.Scanner s = new java.util.Scanner(is).useDelimiter("\\A");
        return s.hasNext() ? s.next() : "";
    }
    @Test
    public void testWarmContext() throws JsonLdError, IOException {
        ClassLoader cl = Thread.currentThread().getContextClassLoader();
        //[{"Content-Location": "https://nonexisting.com/mycontext.jsonld","X-Classpath":"mycontext.jsonld","Content-Type": "application/ld+json"}]
        System.out.println(convertStreamToString(cl.getResourceAsStream("jarcache.json")));
        //{"@context": {"@base": "http://purl.org/dc/terms/"}}
        System.out.println(convertStreamToString(cl.getResourceAsStream("mycontext.jsonld")));

        // com.github.jsonldjava.core.JsonLdError: loading remote context failed: https://nonexisting.com/mycontext.jsonld
        Object jsonObject = JsonUtils.fromString("{\"@context\":[\"https://nonexisting.com/mycontext.jsonld\"]}");

        // Create a context JSON map containing prefixes and definitions
        Map context = new HashMap();
        // Create an instance of JsonLdOptions with the standard JSON-LD options
        JsonLdOptions options = new JsonLdOptions();
        // Customise options...
        // Call whichever JSONLD function you want! (e.g. compact)
        Object compact = JsonLdProcessor.compact(jsonObject, context, options);
        // Print out the result (or don't, it's your call!)
        System.out.println(JsonUtils.toPrettyString(compact));
    }
}
```

**Comment by ansell** [comment]
The existing tests for this functionality are at: 

https://github.com/jsonld-java/jsonld-java/blob/master/core/src/test/java/com/github/jsonldjava/utils/JarCacheTest.java

I am not sure when I will get a chance to work through your test case, but if you could create a pull request with your regression test added to JarCacheTest and the related files then I will look at it when I am able and see where the bug may be.

**Comment by ansell** [comment]
Closing based on lack of feedback and the JarCacheTest that is run in the testsuite regularly. Reopen if you still have a query about it.

**Comment by earcam** [comment]
Setting disallow remote context loading to true triggers exception before jarcache.json is used
Confirmed behaviour in version 0.12.3
