### ISSUE TITLE
Release 0.9 if it works with schema.org

### ISSUE THREAD

**Issue by tfrancart** [jsonld-java/jsonld-java#186]
I saw specific commits were done in August to make sure jsonld-java works with the latest schema.org update that new redirects to its actual JSONLD context file, when requested. I am working with 0.8.3 which apparently doesn't work with schema.org.
I don't know if it would be possible to release v0.9 that fixes this ? this would be very convenient.

Many thanks

**Comment by ansell** [comment]
0.9.0 that should work more reliably with schema.org has been released to Sonatype and should be available on Maven Central in a few hours. Still no clue on why schema.org broke compatibility with Apache HTTP Client, but the workaround of using java.net.URL seems to be stable.

**Comment by tfrancart** [comment]
Thanks, maybe this thread can give some explanations : https://lists.w3.org/Archives/Public/public-schemaorg/2016Sep/0073.html ?

**Comment by ansell** [comment]
No problems. I have opened issue #188 to check what support we currently have for following redirects.
