### ISSUE TITLE
JsonLdProcessor.normalize() looses the options' DocumentLoader

### ISSUE THREAD

**Issue by NicolasRouquette** [jsonld-java/jsonld-java#193]
While working on https://github.com/jsonld-java/jsonld-java-tools/issues/2, I stumbled on a problem in [JsonLdProcessor.normalize()](https://github.com/jsonld-java/jsonld-java/blob/master/core/src/main/java/com/github/jsonldjava/core/JsonLdProcessor.java#L584):

```
 public static Object normalize(Object input, JsonLdOptions options) throws JsonLdError {

        final JsonLdOptions opts = new JsonLdOptions(options.getBase());
        opts.format = null;
        final RDFDataset dataset = (RDFDataset) toRDF(input, opts);

        return new JsonLdApi(options).normalize(dataset);
    }
```

The problem is that the `documentLoader` of the original `options` is lost in the call to `toRDF` which affects `expand`; in particular if it the input happens to be a String IRI of a document to load (see [here](https://github.com/jsonld-java/jsonld-java/blob/master/core/src/main/java/com/github/jsonldjava/core/JsonLdProcessor.java#L114)) or if it becomes necessary to parse the context of an element during expansion (see [here](https://github.com/jsonld-java/jsonld-java/blob/master/core/src/main/java/com/github/jsonldjava/core/JsonLdApi.java#L543)).

**Comment by ansell** [comment]
A workaround until there is a fix would be for you to copy-paste that method and modify it locally to suit your purposes.

In the meantime I will look into how to support persisting the JsonLdOptions through that method.
