### ISSUE TITLE
lower casing language types introduces bugs in some cases

### ISSUE THREAD

**Issue by eroux** [jsonld-java/jsonld-java#199]
The current behavior seems to be to lower case all language tags ([here in the code](https://github.com/jsonld-java/jsonld-java/blob/4aa9f617240c2876b343c1abd8d5dfa5d1285538/core/src/main/java/com/github/jsonldjava/core/JsonLdApi.java#L635)). 

The JSON-LD spec only seems to indicate that lang tags should be BCP-47, and does not say anything about the case. The BCP47 spec states [page 7](https://tools.ietf.org/html/rfc5646#page-7) that:
 - the language tags should be treated in a case insensitive manner
 - in accordance with [ISO15924](https://en.wikipedia.org/wiki/ISO_15924), the name of the script part should start with an upper case letter, and the [IANA list](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) contains a few of these, such as the one I got a few problems with: `zh-Latn-pinyin`

So, while jsonld-java is not strictly wrong in lower casing the language tag, it would help if it either:
 - leaves the tag untouched
 - or parses the tag and makes it canonical (keeping the upper cased first letter of the script part)

Sadly, there doesn't seem to be any library for BCP47 parsing in Java.

The annoyance manifested as follows (in unit testing):
- I have an RDF set with some literals tagged as `zh-Latn-pinyin`
- I want to compare it with what it should be, which is a file on disk written with jsonld-java (thus containing lower-cased language tags)
- I ask Jena if the two graphs are isomorphic, jena answers no because the language tags are different

So, although this actually a bug in Jena, I think it would be less confusing if jsonld-java changed its behavior, as it's not really nice to make the effort to have canonical BCP47 tags and have them decanonicalized by jsonld-java.

**Comment by eroux** [comment]
I've reported the bug in Jena: https://issues.apache.org/jira/browse/JENA-1377

**Comment by afs** [comment]
See `Locale.toLanguageTag()`

**Comment by eroux** [comment]
Good idea, I can confirm that

```java
System.out.println(Locale.forLanguageTag("zh-Latn-pinyin").toLanguageTag());
System.out.println(Locale.forLanguageTag("ZH-latn-pinyin").toLanguageTag());
```

prints

```
zh-Latn-pinyin
zh-Latn-pinyin
```

**Comment by afs** [comment]
RDF 1.1 allows processors to lower case language tags. This is partially a relic from RDF 1.0 which was at odds with the BCP47 canonical form.

**Comment by afs** [comment]
Jena's graph isomorphism is not a based on values but on term comparison. Details on JENA-1377.

**Comment by eroux** [comment]
Well, in short, what I understand is that lower casing language tags is not a good idea, and that canonicalizing them is only a slightly better one, so maybe the best solution is not to touch the lang tags?

**Comment by ansell** [comment]
I will look into this when I get a chance. The JVM has full compliance with BCP47 from Java-7, using the Locale method you referred to.

**Comment by eroux** [comment]
This is an issue with the spec, not this library
