### ISSUE TITLE
JsonUtils.fromInputStream should expect and ignore BOM

### ISSUE THREAD

**Issue by christopher-johnson** [jsonld-java/jsonld-java#214]
Jackson will not parse BOM and throws JsonParseException.  UTF-8 JSON consuming implementations like `JsonUtils.fromInputStream` should expect and ignore it if a document contains it.   

My specific problem is that I need to deserialize a document that uses a [context](http://wellcomelibrary.org/ld/iiif-ext/0/context.json) that contains a UTF-16 BOM.

Propose to add:
```java
    public static Object fromInputStream(InputStream input) throws IOException {
        // no readers from inputstreams w.o. encoding!!
        BOMInputStream bOMInputStream = new BOMInputStream(input,false, ByteOrderMark.UTF_8,
                ByteOrderMark.UTF_16BE, ByteOrderMark.UTF_16LE,
                ByteOrderMark.UTF_32BE, ByteOrderMark.UTF_32LE );
        return fromInputStream(bOMInputStream, "UTF-8");
    }
```

**Comment by ansell** [comment]
Thanks, I made some small changes to host the file locally so I could verify it had a BOM, and to ensure it stays that way to keep testing that functionality in future.
