### ISSUE TITLE
How can I get a representation of a JSON-LD with compacted values?

### ISSUE THREAD

**Issue by omare13** [jsonld-java/jsonld-java#216]
Hello everyone,

I was wondering what the capabilities of the compact algorithm are --> `JsonLdProcessor.compact(JSON-LD, context, options)`

By [specification ](https://www.w3.org/TR/json-ld-api/#compaction-algorithms) and inspecting the code, it is said the API covers compaction of values. Therefore, I thought the API is providing [type coercion](https://json-ld.org/spec/latest/json-ld/#type-coercion) capabilities.

However, when I run this code loading a local JsonLD file which includes a `@context` section:
```
InputStream is = new FileInputStream("data.jsonld");  
	    Object jsonld = JsonUtils.fromInputStream(is);  
	    
	    JsonLdOptions options = new JsonLdOptions();
	    options.setCompactArrays(false);

	    Map context = new HashMap();
	
	    Object compact = JsonLdProcessor.compact(jsonld, context, options);
	    System.out.println(JsonUtils.toPrettyString(compact));
```

I'm not getting the desired results but the same local JsonLD file content with no context.

I've tried to include some mappings in the context variable, but even if I include some tuples inside the context (propertyName, propertyURI), the usage of these properties in the `@graph` section is still the same (expanded, including `@type` and `@value`).

Am I missing something about the context argument of the compact method? Does this algorithm actually resolve type coercion?

Hope I can get a hint on this.
Thanks in advance.

**Comment by ansell** [comment]
Hi @omare13,

It looks like you have linked to a draft of JSON-LD-1.1. This library currently implements JSON-LD-1.0, with a few minor changes to support some of the new 1.1 features.

If you want to implement features from 1.1 I am happy to review them.

**Comment by omare13** [comment]
Dear @ansell ,

Thank you for your quick answer. Type coercion is a feature of JSON-LD-1.0 as well. It can be found at [its specification](https://www.w3.org/TR/2014/REC-json-ld-20140116/#type-coercion) and its seems  to allow value representation "without requiring the data type to be specified with each piece of data".

Therefore, having a JSON-LD example as follows:

```
{
"@context":{
    	"xsd": "http://www.w3.org/2001/XMLSchema#",
    	"age": "http://xmlns.com/foaf/0.1/age",
	"unemployed": "http://example.com/unemployed",
    	"homepage": {
		"@id":"http://xmlns.com/foaf/0.1/homepage",
		"@type":"@id"
	}
},

"@graph":[

	{
	"@id":"http://example.com/people#john",
	"unemployed":{
		"@type":"xsd:boolean",
		"@value":"true"
	},
	"age":{
		"@type":"xsd:integer",
		"@value":"23"
	},
	"homepage":[
		"http://personal.example.org/john",
		"http://work.example.com/jsmith/"
	]
	},

	{
	"@id":"http://example.com/people#mary",
	"unemployed":{
		"@type":"xsd:boolean",
		"@value":"false"
	},
	"age":{
		"@type":"xsd:integer",
		"@value":"25"
	},
	"homepage":[
		"http://personal.example.org/mary",
		"http://work.example.com/mjane/"
	]
	}
]
}
```

Type coercion allows us to extend the `@context` including type information so it is not duplicated through the `@graph` ,resulting in the above example as follows:

```
{
"@context":{
    	"xsd": "http://www.w3.org/2001/XMLSchema#",
    	"age": {
		"@id":"http://xmlns.com/foaf/0.1/age",
		"@type":"xsd:integer"	
	},
	"unemployed": {
		"@id":"http://example.com/unemployed",
		"@type":"xsd:boolean"
	},
    	"homepage": {
		"@id":"http://xmlns.com/foaf/0.1/homepage",
		"@type":"@id"
	}
},

"@graph":[

	{
	"@id":"http://example.com/people#john",
	"unemployed":"true",
	"age":"23",
	"homepage":[
		"http://personal.example.org/john",
		"http://work.example.com/jsmith/"
	]
	},

	{
	"@id":"http://example.com/people#mary",
	"unemployed":"false",
	"age":"25",
	"homepage":[
		"http://personal.example.org/mary",
		"http://work.example.com/mjane/"
	]
	}
]
}
```
This is the result I expected when I run the code I mentioned, but it was not the case. I expected so because JSON-LD 1.0 API Spec Value Compaction algorithm provide this type coercion feature.
Looking at your code it seems that JsonLdProcessor's compact method calls to JsonLdApi's compact method to perform value compaction.

So please let me reformulate the question: Does your compaction algorithm implementation actually perform type coercion (value compaction)?

**Comment by ansell** [comment]
Sorry, there does not appear to be any part of the JSON-LD compaction algorithm that creates a type entry in the context after finding the type in use in the graph. You will need to take this to the jsonld mailing lists to see how that could be supported in a new JSON-LD version.
