### ISSUE TITLE
More documentation needed in order to use the library

### ISSUE THREAD

**Issue by rodrigodesalvobraz** [jsonld-java/jsonld-java#231]
I think that referring to the JAVA-LD API specification is not enough to tell users how to use JSONLD-JAVA. In particular, it is not clear what Java types are involved (and of course the language-neutral JSON-LD API does not say anything about that).

By using an IDE's auto-assist or by looking at the source code, a user can find out what these types are, but even then most of the return types are Object so I don't think users will be able to tell how to use them in order to access JSON-LD object properties.

I've spent some time on it and did not make much progress. I've described the [thought process](https://stackoverflow.com/questions/49715194/how-to-traverse-navigate-and-access-objects-from-a-json-ld-files-with-jsonld-ja) at StackOverflow in more detail.

**Comment by rodrigodesalvobraz** [comment]
The answer at StackOverflow points out that there is enough information in the comments of the example code to figure how to use the library to traverse the data, so I am closing the issue. Still, it seems that more structured documentation would be a good thing.

**Comment by ansell** [comment]
Unfortunately, JSON doesn't map onto type systems well. The usual type is ``Map<String, Object>`` but even that has cases where it doesn't fit well, such as when the top element is an array. Internally there are many ``instanceof`` checks to deal with cases where either ``List<String>`` or ``Map<String, Object>`` can be in a given location.

Any pull requests improving on the documentation based on your experience would be appreciated.
