### ISSUE TITLE
In conversion jsonld to rdf some data are missing.

### ISSUE THREAD

**Issue by giatrakister** [jsonld-java/jsonld-java#232]
Hi, 

i use jsonld java to convert jsonld data to rdf. My jsonld data are like that:

[jsonld.txt](https://github.com/jsonld-java/jsonld-java/files/1931923/jsonld.txt)

and the code i used for the conversion is:

             InputStream inputStream = new FileInputStream("C:\\Users\\Desktop\\jsonLD.json");
            Object jsonObject = JsonUtils.fromInputStream(inputStream);
             Map context = new HashMap();
             JsonLdOptions options = new JsonLdOptions();
            Object myRdf = JsonLdProcessor.toRDF(jsonObject, options);

but the results does not include all the data, only the nested ones and the rdf format is not as expected:
[resultsRDF.txt](https://github.com/jsonld-java/jsonld-java/files/1931935/resultsRDF.txt)

Is there any intermediate step that i should follow?

thanx!

**Comment by giatrakister** [comment]
I think that the jsonld is not correct. My starting point is a json file, are there any guidelines for json to jsonld convertion?

**Comment by ansell** [comment]
Hi @giatrakister, those files are too large to investigate. Can you submit a smaller test file that shows where it may be breaking?

In terms of a json to jsonld conversion question, you could ask on the JSON-LD mailing lists for assistance.

**Comment by vcharpenay** [comment]
I ran into the same problem and I noticed that only objects with `@id` defined as relative IRIs with no `@base` disappear, as follows:

```java
Object o = JsonUtils.fromString("{\"@id\":\"relativeURIWithNoBase\",\"@type\":\"http://example.org/SomeRDFSClass\"}");
System.out.println(JsonLdProcessor.toRDF(o));

// expected: {@default=[{subject={type=IRI, value=./relativeURIWithNoBase}, predicate={type=IRI, value=http://www.w3.org/1999/02/22-rdf-syntax-ns#type}, object={type=IRI, value=http://example.org/SomeRDFSClass}}]}
// actual:   {@default=[]}
```

The section on RDF serialization [mentions _well-formed_ IRIs](https://w3c.github.io/json-ld-api/#deserialize-json-ld-to-rdf-algorithm), which relative IRIs without base are not. @giatrakister, passing a base IRI as JSON-LD option will probably work, as follows:

```java
Object o = JsonUtils.fromString("{\"@id\":\"relativeURIWithNoBase\",\"@type\":\"http://example.org/SomeRDFSClass\"}");
System.out.println(JsonLdProcessor.toRDF(o, new JsonLdOptions("http://example.org/")));

// output: {@default=[{subject={type=IRI, value=http://example.org/relativeURIWithNoBase}, predicate={type=IRI, value=http://www.w3.org/1999/02/22-rdf-syntax-ns#type}, object={type=IRI, value=http://example.org/SomeRDFSClass}}]}
```

However, @ansell, it seems there is another bug in my case: the base IRI argument is ignored if it uses an exotic URI scheme, like [`tag:`](https://tools.ietf.org/html/rfc4151). The following also returns an empty graph:

```java
Object o = JsonUtils.fromString("{\"@id\":\"relativeURIWithNoBase\",\"@type\":\"http://example.org/SomeRDFSClass\"}");
System.out.println(JsonLdProcessor.toRDF(o, new JsonLdOptions("tag:example/")));

// expected: {@default=[{subject={type=IRI, value=tag:example/relativeURIWithNoBase}, predicate={type=IRI, value=http://www.w3.org/1999/02/22-rdf-syntax-ns#type}, object={type=IRI, value=http://example.org/SomeRDFSClass}}]}
// actual:   {@default=[]}
```

**Comment by fsteeg** [comment]
>  [...] another bug in my case: the base IRI argument is ignored if it uses an exotic URI scheme, like `tag:`

I took a look at this and it seems the problem here is not the scheme itself, but the fact that the base IRI is opaque (not hierarchical), meaning the scheme-specific part does not start with a slash. With `new JsonLdOptions("tag:/example/")` I do get the expected output.

And while that works, it seems the hierarchical part should actually start with *two* slashes, see https://w3c.github.io/json-ld-syntax/#base-iri, https://tools.ietf.org/html/rfc3986#section-5.1, https://tools.ietf.org/html/rfc3986#section-4.3, and https://tools.ietf.org/html/rfc3986#appendix-A

**Comment by fsteeg** [comment]
Fixed in master, closing. See https://github.com/jsonld-java/jsonld-java/pull/260.
