### ISSUE TITLE
Single Blank Node to Nested Object

### ISSUE THREAD

**Issue by FabiApfelkern** [jsonld-java/jsonld-java#233]
Does the library support the conversion from a single blank node to a nested object? If not, is this a planed feature? More details here: https://stackoverflow.com/questions/50588066/json-ld-blank-node-to-nested-object-in-apache-jena

**Comment by fsteeg** [comment]
This issue seems to be answered, closing.

@FabiApfelkern: feel free to reopen or ask @jschnasse in his stackoverflow answer linked above.

**Comment by jschnasse** [comment]
Yes, you can use the [JsonLdProcessor.frame(..)](https://github.com/jsonld-java/jsonld-java/blob/master/core/src/main/java/com/github/jsonldjava/core/JsonLdProcessor.java#L297) method. Like shown in the SO example:

`JsonLdProcessor.frame(json, getFrame(), new JsonLdOptions());`
