### ISSUE TITLE
Question about httpclient-osgi

### ISSUE THREAD

**Issue by HansBrende** [jsonld-java/jsonld-java#235]
@ansell is there a reason for using `httpclient-osgi` and `httpcore-osgi` (which includes transitive dependencies on `commons-codec`, `httpclient`, `httpmime`, `httpclient-cache`, `fluent-hc`, `httpcore`, and `httpcore-nio`), when (I believe) the project only requires `httpclient`, `httpclient-cache`, and `httpcore`? 

I ask in reference to [ANY23-369](https://issues.apache.org/jira/browse/ANY23-369), which I resolved in [this pull request](https://github.com/apache/any23/pull/103) by manually excluding all of those extra dependencies from the `jsonld-java` dependency, after noting that RDF4J did the same thing in the [`rdf4j-rio-jsonld` pom](https://github.com/eclipse/rdf4j/blob/master/rio/jsonld/pom.xml).

**Comment by ansell** [comment]
There were OSGi users who were implementing things separately themselves, so I switched to using the upstream OSGi bundles and switched jsonld-java to be a bundle https://github.com/jsonld-java/jsonld-java/issues/87 . I don't develop using OSGi myself, so I am not familiar with the consequences of that, but it should just be a matter of excluding the OSGi artifacts if they are conflicting with another part of your classpath and that should be as far as you need to go.
