### ISSUE TITLE
apply the @embed option to an existing JSON-LD object.

### ISSUE THREAD

**Issue by marco-brandizi** [jsonld-java/jsonld-java#238]
Sorry to open an issue to ask this, it might be a problem anyway.

I'm looking for a way to transform a JSON-LD object so that the `@embed = @always` option is applied. Only `JsonLdProcessor.frame()` seems to consider `JsonLdOptions.setEmbed()`, `.compact()` doesn't make this change. Is there a way to do it without framing?

This is coming from [elsewhere](https://stackoverflow.com/questions/51966888/writing-embedding-json-ld-from-jena), I actually would like to obtain an embedded output from a Jena model, but I cannot find a way in Jena, so my second best option would be to re-process the JSON-LD coming from RIOT (which is using jsonld-java).

**Comment by marco-brandizi** [comment]
Thanks @eroux, I was hoping that it is intended for general use, i.e., "embed when you build the JSON", good to know how it actually is.

**Comment by eroux** [comment]
You're welcome! maybe you  an close the issue?
