### ISSUE TITLE
Make additional methods on Context visible

### ISSUE THREAD

**Issue by jgustie** [jsonld-java/jsonld-java#244]
I am working on a project where it would be useful to access some of the parsed information from the `Context`, however only `getContainer` and `isReverseProperty` are public at this time. Both `getTypeMapping` and `getLanguageMapping` are currently private. Would it be possible to make those two additional methods public?

**Comment by ansell** [comment]
No problems, done. There was a recent release so will wait a bit and see if there are any further PRs to add to the next release.

**Comment by jgustie** [comment]
Thanks! I will keep an eye out for the release.
