### ISSUE TITLE
How do I query the parsed jsonld document for query keys?

### ISSUE THREAD

**Issue by jeyendranbalakrishnan** [jsonld-java/jsonld-java#246]
I am able to successfully parse json-ld documents now, using jsonld-java.
Using the compact() API, I get back a Map<String, Object>, where the keys are string IRIs, basically prefixed by the context URI and suffixed by individual keys.
I have two questions regarding how to query the parsed object to get specific data out:
1. The values returned by the API for each map key in the returned Map<String, Object> is an arbitrary object. What is the best way to walk down the tree of starting from a known top level key? For instance, how do I know if a given value is a primitive (String, integer, double, date, etc) rather than a JSON object that needs to be queried using it's methods? And so down the tree at any level? 
2. If I used the API on arbitrary json-ld documents, which have their own contexts not known at coding time, how do I format the query keys with the unknown context prefix at query time?

Thank you!

**Comment by jeyendranbalakrishnan** [comment]
Thanks for the reply, clarified a lot of things:  
1. Regarding known vs unknown structure, my use-case is parsing and extracting the JSON-LD objects from arbitrary web pages from web sites not known at coding time, like news articles, blogs posts, review pages, etc. So I'm not sure whether everyone will use only "schema.org" contexts. I guess I could start with schema.org and then log instances of other contexts that occur, and manually add support for each one as they are encountered.
2. Regarding how to query for items. I would like to query for certain entities which are likely to be present for several different types, for example publisher name, which can occur in CreativeWork and its sub types, Product and Review types in schema.org. Currently, I only know how to do this by manuallying coding the JSON path to publisher name for all these types. And I have to do this for all such entities, example date of publication, etc. It would be nice to have a simple Java API to query for the presence of, and extract values of, arbitrary leaf entities in the JSON LD object emitted by compact(), without going through the trouble and hassle of a heavier-duty RDF store and SPARQL. :-)

**Comment by jeyendranbalakrishnan** [comment]
Your comments are very helpful, I'm understanding all this json-ld stuff better now :-)
For my application, the use-case is to parse, process and discard Web pages as they are fetched, so I think it would still be better to work directly with the Map<String, Object> returned by the compact() method., instead of writing the parsed object to an RDF4J store and then running SPARQL queries. Mainly the need is to extract specific properties, if they exist, from this object.
I also found that almost all web pages will use the schema.org context, because this is Google's standard for SEO. So it suffices for me to restrict to this schema. 
For implementing the queries, the JsonPath API seems very appropriate. Thanks for the tip.
I have one final question: To form the JsonPath queries that can be applied to the output of compact(), I have to use the fully qualified path components in the query, right? like "$.http://www.schema.org/Person.http://www.schema.org/name" etc., right?

**Comment by ansell** [comment]
The default output from JSONLD-Java is a non-library-specific Map. You may need to serialise the compacted output to JSON using ``JsonUtils.toPrettyString`` and reparse it using JsonPath to get access to it that way but not familiar with the full capabilities of JsonPath. 

The path you would use that way would be exactly the object attributes in the JSON created by ``JsonUtils.toPrettyString``. The compact representation will not give you the full IRIs as object attributes, so if you want to go that way you may prefer ``expand`` rather than ``compact``.

**Comment by fsteeg** [comment]
I think this has been resolved, closing.
