### ISSUE TITLE
Exception whilst parsing schema.org properties defined as "Text" or "URL".

### ISSUE THREAD

**Issue by davidcockbill** [jsonld-java/jsonld-java#248]
I am experiencing strange behaviour in the results from the JSON-LD parser, when parsing with the schema.org context.
However, I am uncertain whether the issue with the (a) JSON-LD parser, (b) The context information from schema.org, or (c) me just not understanding something fundamental!

So given the following (taken from https://www.bbc.co.uk/programmes/b0brzkzx):

```
      <script type="application/ld+json">
      {
        "@context":"http://schema.org",
        "@type":"Role",
        "roleName":"Production Company"
      }
      </script>
```

I get the following error:

"java.lang.IllegalArgumentException: Illegal character in path at index 10: Production Company".
This occurs during the expansion of the value for the https://schema.org/roleName property.

Specifically in method expandValue() in Context.java:

```
if (td != null && JsonLdConsts.ID.equals(td.get(JsonLdConsts.TYPE))) {
    // TODO: i'm pretty sure value should be a string if the @type is
    // @id
    rval.put(JsonLdConsts.ID, expandIri(value.toString(), true, false, null, null));
    return rval;
}
```

This follows Point 1 of the Value Expansion Algorithm (Section "7.2 Value Expansion" in https://www.w3.org/TR/2014/REC-json-ld-api-20140116/)

This is caused as follows:
During expansion, the cache for the schema.org is populated (essentially with the result of "wget http://schema.org/docs/jsonldcontext.json").

The https://schema.org/roleName property is defined as follows in the resulting context file:

```
"roleName": { "@id": "schema:roleName", "@type": "@id"},
 ```

The "@type" being of value "@id" means it will be expanded as an IRI.

According to the document, https://schema.org/roleName can be of type "Text" or "URL".

So to Summarise:
- We get an exception thrown when processing https://schema.org/roleName as a "Text" value (if there is a space (invalid URI character) in the value).
- This is due to the schema.org context stamping it as a URL ("@type": "@id"); which causes IRI expansion. Rather that treating it as "text", as intended.
 
(a) Is there a hole in the value expansion algorithm (just wondering because of the TODO comment shown earlier)?
(b) Is the schema.org downloaded context wrong?
(c) I'm doing something wrong?

Incidentally I also get unexpected behaviour (IMHO) for https://schema.org/acceptsReservations which can have a value type of "Boolean", "Text" or "URL"; for a similar reason. A value of "True" is expanded as URI.

Please advise and close if not a perceived bug in the project.

Note: The TODO goes right back to the first commit of Context.java (163b74ff225bc7b16b1968b27b92f8e4d379cad4)

**Comment by davidcockbill** [comment]
Discusion on schema.org, [here](https://github.com/schemaorg/schemaorg/issues/51).

**Comment by fsteeg** [comment]
Hi @davidcockbill! Thanks for the detailed issue. Reading the discussion on schema.org you linked to, there seem to be two possible solutions:

Either we explicitly state in the data that it is a value, not a URI:

```json
{
  "@context": "http://schema.org",
  "@type": "Role",
  "roleName": [{"@value": "Production Company"}]
}
```

Or we override the context entry:

```json
{
  "@context": ["http://schema.org", {"roleName" : {"@id": "schema:roleName"}}],
  "@type": "Role",
  "roleName": "Production Company"
}
```

I've tested both structures with jsonld-java, see https://github.com/fsteeg/jsonld-java/commit/29c195c03cd50d5c41f7f9c4ed3839f296265f4f.

From the discussion on schema.org I'd say people think that the schema.org context should not do what it's doing, but from the processor's side, jsonld-java seems to behave correctly. Feel free to reopen.

**Comment by davidcockbill** [comment]
Hi @fsteeg.

Thanks for looking at this. Unfortunately, for the project I am working on we accept JSON-LD from all sources; the BBC in this case. We have no control over how they define their data. So the workarounds will not work for us.

From your analysis, this looks to be a schema.org problem. So hopefully they can sort it out.

In case anyone else hits this issue, the workaround I have used is to populate the schema.org cache (See README.md in the repository) with doctored data. Note that you need to do this for HTTP and HTTPS versions of the context!

**Comment by fsteeg** [comment]
@davidcockbill Thanks for posting your workaround!
