### ISSUE TITLE
Getting OutOfMemoryError while try to frame JsonLd object using java

### ISSUE THREAD

**Issue by a-rajasekar** [jsonld-java/jsonld-java#274]
Getting OutOfMemoryError while try to frame JsonLd object using java, please help me to resolve this issue

graphToFrame type is NQUARDS

 RDFDataset dataSet = RDFDatasetUtils.parseNQuads(graphToFrame);
JsonLdOptions options = new JsonLdOptions();
frameData = JsonUtils.fromString(frame);
Object rval = new JsonLdApi(options).fromRDF(dataSet);
Object framedJsonObject = JsonLdProcessor.frame(rval, frameData, options);

Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
at java.util.HashMap.newNode(Unknown Source)
at java.util.HashMap.putVal(Unknown Source)
at java.util.HashMap.put(Unknown Source)
at java.util.HashSet.add(Unknown Source)
at java.util.AbstractCollection.addAll(Unknown Source)
at java.util.HashSet.(Unknown Source)
at com.github.jsonldjava.core.JsonLdApi.removeDependents(JsonLdApi.java:1681)
at com.github.jsonldjava.core.JsonLdApi.removeEmbed(JsonLdApi.java:1676)
at com.github.jsonldjava.core.JsonLdApi.frame(JsonLdApi.java:1456)

**Comment by dr0i** [comment]
Welcome @a-rajasekar. Can you provide the data you used ?

**Comment by a-rajasekar** [comment]
Hi 

> Welcome @a-rajasekar. Can you provide the data you used ?

Sorry for the inconvenience I am not in the position to share data but I can share you the frame.same functionality is working for minimal size data(101 kb) but I am facing issues if the size is huge(5112 kb)
curriculumConceptSchemeMappingFrame={ 
    "@context" : { 
    "locCode": "http://schema.softtech.com/ns/curriculum#locCode", 
    "locLabel": "http://schema.softtech.com/ns/curriculum#locLabel", 
    "ABGUID": "http://schema.softtech.com/ns/curriculum#ABGUID", 
    "description": "http://purl.org/dc/terms/description", 
   "order": { 
     "@id": "http://schema.softtech.com/ns/common#order", 
     "@type": "http://www.w3.org/2001/XMLSchema#integer" 
   },
    "definition": { 
        "@id": "http://schema.softtech.com/ns/curriculum#definition", 
      "@type":"@id" 
   	}, 
    "isPartOf": { 
       "@id": "http://schema.softtech.com/ns/curriculum#isPartOf", 
       "@type": "@id" 
   }, 
   "hasPart": { 
       "@id": "http://schema.softtech.com/ns/curriculum#hasPart", 
       "@type": "@id", 
       "@container": "@set" 
   }, 
   "centrallyRelated": { 
       "@id": "http://schema.softtech.com/ns/learn/centrallyRelated", 
       "@type": "@id", 
        "@container": "@set" 
   }, 
    "keyRelated": { 
       "@id": "http://schema.softtech.com/ns/learn/keyRelated", 
             "@type": "@id", 
       "@container": "@set" 
   }, 
   "peripherallyRelated": { 
       "@id": "http://schema.softtech.com/ns/learn/peripherallyRelated", 
            "@type": "@id", 
       "@container": "@set" 
   }, 
        "centrallyRelated_print": { 
       "@id": "http://schema.softtech.com/ns/learn/centrallyRelated_print", 
       "@type": "@id", 
        "@container": "@set" 
   }, 
   "keyRelated_print": { 
       "@id": "http://schema.softtech.com/ns/learn/keyRelated_print", 
             "@type": "@id", 
       "@container": "@set" 
   }, 
   "peripherallyRelated_print": { 
       "@id": "http://schema.softtech.com/ns/learn/peripherallyRelated_print", 
            "@type": "@id", 
       "@container": "@set" 
   }, 
   "centrallyRelated_digital": { 
       "@id": "http://schema.softtech.com/ns/learn/centrallyRelated_digital", 
       "@type": "@id", 
        "@container": "@set" 
   }, 
    "keyRelated_digital": { 
       "@id": "http://schema.softtech.com/ns/learn/keyRelated_digital", 
             "@type": "@id", 
       "@container": "@set" 
   }, 
   "peripherallyRelated_digital": { 
       "@id": "http://schema.softtech.com/ns/learn/peripherallyRelated_digital", 
            "@type": "@id", 
       "@container": "@set" 
   }, 
   "centrallyRelated_printDigital": { 
       "@id": "http://schema.softtech.com/ns/learn/centrallyRelated_printDigital", 
       "@type": "@id", 
        "@container": "@set" 
   }, 
    "keyRelated_printDigital": { 
       "@id": "http://schema.softtech.com/ns/learn/keyRelated_printDigital", 
             "@type": "@id", 
       "@container": "@set" 
   }, 
   "peripherallyRelated_printDigital": { 
       "@id": "http://schema.softtech.com/ns/learn/peripherallyRelated_printDigital", 
            "@type": "@id", 
       "@container": "@set" 
   }, 
    "inStructure": { 
       "@id": "http://schema.softtech.com/ns/curriculum#inStructure", 
       "@type": "@id" 
   }, 
   "levelRange": "http://schema.softtech.com/ns/common#levelRange", 
   "minLevel": { 
       "@id": "http://schema.softtech.com/ns/common#minLevel", 
       "@type": "@id" 
   }, 
   "maxLevel": { 
       "@id": "http://schema.softtech.com/ns/common#maxLevel", 
       "@type": "@id" 
   }, 
   "label":"http://www.w3.org/2000/01/rdf-schema#label", 
   "notation":"http://www.w3.org/2004/02/skos/core#notation", 
   "id": "@id", 
   "type": "@type", 
"ProcessConcept":  "http://schema.softtech.com/ns/learn/ProcessConcept", 
"UnderstandingConcept":  "http://schema.softtech.com/ns/learn/UnderstandingConcept", 
"STFkConcept":  "http://schema.softtech.com/ns/learn/STFkConcept", 
"IntermediaryConcept":  "http://schema.softtech.com/ns/learn/IntermediaryConcept",
"Concept":  "http://www.w3.org/2004/02/skos/core#Concept", 
   "LOCDefinition": "http://schema.softtech.com/ns/curriculum#LOCDefinition", 
   "LearningOutcomeOrCompetency": "http://schema.softtech.com/ns/curriculum#LearningOutcomeOrCompetency", 
   "inScheme": { 
            "@id": "http://www.w3.org/2004/02/skos/core#inScheme" 
        }, 
        "prefLabel": { 
            "@id": "http://www.w3.org/2004/02/skos/core#prefLabel", 
            "@container": "@language" 
        }, 
        "spanishDescription": { 
            "@id": "http://www.w3.org/2004/02/skos/core#spanishDescription", 
            "@container": "@language" 
        }, 
"intermediaryStatementCode": { 
            "@id": "http://www.w3.org/2004/02/skos/core#intermediaryStatementCode", 
            "@container": "@language" 
        }, 
        "about": { 
            "@id": "http://schema.org/about", 
            "@type": "@id" 
        } 
 }, 
"inStructure":{} 
}

**Comment by dr0i** [comment]
@a-rajasekar 5MB of data shouldn't be a problem.  I can assume you have not set java's `-Xmx` to an unusual small size? The problem could  be a memory leak, maybe there is some cyclic graph problem there. This can be analyzed, but not without data. Maybe you can somehow rewrite the data values if these are too private?

**Comment by a-rajasekar** [comment]
Thanks for your quick and valuable response I tested Java heap size upto to 16gb.As you specified in the comment the issue could be cyclic graph problem. I will try to share some sample data to verify it in your end

**Comment by a-rajasekar** [comment]
Is there any option to verify cyclic graph?

**Comment by dr0i** [comment]
Not of that I am aware of it. There is a [mechanism built in to throw an Exception if a cyclic IRI mapping in the context definition is detected](https://github.com/jsonld-java/jsonld-java/blob/master/core/src/main/java/com/github/jsonldjava/core/Context.java#L319). If that had happened you would have seen the Exception. So I think it's rather something undetected yet.

**Comment by dr0i** [comment]
As long as this is not reproducible (non available test data) this issue must be closed.
