### ISSUE TITLE
Values with the datatype XSD_DECIMAL should not be canonicalized.

### ISSUE THREAD

**Issue by jhg023** [jsonld-java/jsonld-java#275]
Beginning on [line 668](https://github.com/jsonld-java/jsonld-java/blob/master/core/src/main/java/com/github/jsonldjava/core/RDFDataset.java#L668) of `RDFDataset.java`, we have the following snippet:
```java
// canonical double representation
final DecimalFormat df = new DecimalFormat("0.0###############E0");
df.setDecimalFormatSymbols(DecimalFormatSymbols.getInstance(Locale.US));
return new Literal(df.format(value),
        datatype == null ? XSD_DOUBLE : (String) datatype, null);
```
If the datatype of `value` happens to be `XSD_DECIMAL`, it's still canonicalized with `E0`, which goes against the [specification](http://books.xmlschemata.org/relaxng/ch19-77057.html).

The specification restrictions state the following (emphasis, mine):
>The decimal separator is always a point (.), and no separation at the thousand mark may be added. **There is no support for scientific notation**.

It is imperative that this snippet be refactored to **not** canonicalize values of the type `XSD_DECIMAL`.

I will be submitting a PR to address this issue within the next couple hours.

**Comment by ansell** [comment]
Thanks, LGTM
