### ISSUE TITLE
java.net.URI resolution error

### ISSUE THREAD

**Issue by afs** [jsonld-java/jsonld-java#279]
[Reported by](https://lists.apache.org/thread.html/r343f27b3390dfbfd7ce9dcee4576bc532705b39d26923dfb0baf5322%40%3Cusers.jena.apache.org%3E) @ebremer

Summary:

    java.net.URI uri = new java.net.URI("http://mysite.net");
    System.out.println(uri.resolve("picture.jpg"));

returns "http://mysite.netpicture.jpg"

This creates an issue with:
https://github.com/jsonld-java/jsonld-java/blob/66012db2f53b009cedeae50c83b5594b9dd05e11/core/src/main/java/com/github/jsonldjava/utils/JsonLdUrl.java#L283

where the erroneous URI created with URI.resolve() yields "@id" turning into blank nodes.

**Comment by dr0i** [comment]
@afs thx for the report. Issue confirmed.

**Comment by dr0i** [comment]
@afs and @ebremer: fixed and merged into master.
Closing.
