### ISSUE TITLE
Cannot resolve Maven dependency

### ISSUE THREAD

**Issue by charlycou** [jsonld-java/jsonld-java#282]
HI! I'm getting trouble loading the dependency when trying to install [apache-jena-libs dependency](https://mvnrepository.com/artifact/org.apache.jena/apache-jena-libs/3.13.0).

Same result with the following pom.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>test-dependency</artifactId>
    <version>1.0-SNAPSHOT</version>

    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.github.jsonld-java</groupId>
            <artifactId>jsonld-java</artifactId>
            <version>0.12.5</version>
        </dependency>
    </dependencies>
</project>
```

> Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.example:test-dependency:jar:1.0-SNAPSHOT: Failure to find com.github.jsonld-java.jsonld-java:jsonld-java:bundle:v0.12.5 in https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced

Can you reproduce?

**Comment by dr0i** [comment]
Hi @charlycou. Yes, I can reproduce. Trying to investigate.

**Comment by dr0i** [comment]
The `groupId` is wrong. It should be:
```
 <groupId>com.github.jsonld-java.jsonld-java</groupId>
```
Can you try this @charlycou ?

**Comment by charlycou** [comment]
@dr0i, this is working using your `groupId`! Did something change? The wrong` groupId` is mentioned in the documentation. Also I could resolve [org.apache.jena.apache-jena-libs.3.13.0](https://mvnrepository.com/artifact/org.apache.jena/apache-jena-libs/3.13.0) which is using ` jsonld-java/jsonld-java ` as peer-dependency. It now seems to be broken because of this wrong `groupId` ([pom](https://github.com/apache/jena/blob/master/jena-arq/pom.xml))

**Comment by ansell** [comment]
@charlycou I have never heard of jitpack.io. If they have an alternative packaging or different coordinates for our maven artifact you will need to contact their support to discuss it with them.

All of the JSONLD-Java packages are published directly to Maven Central.

**Comment by veselov** [comment]
Just FYI, this is why: https://github.com/jitpack/jitpack.io/issues/3779#issuecomment-1160801082
