### ISSUE TITLE
@reverse with framing does not work 

### ISSUE THREAD

**Issue by tanuja3088** [jsonld-java/jsonld-java#286]
I was trying to use a frame that has @reverse in it and used version of 0.12.4 

I have provided a sample json ld input and frame 
https://tinyurl.com/yd55h8d3

I get the intended output when using playground but it fails when we try to use 
JsonLdProcessor.frame(json, getFrame(), new JsonLdOptions());

**Comment by umbreak** [comment]
@reverse key is a Json-LD 1.1 feature and Json-LD 1.1 is not fully supported in Json-LD Java so far.

**Comment by fsteeg** [comment]
To clarify, as far as I understand, the `@reverse` keyword does exist in 1.0 (see [reverse-properties](https://json-ld.org/spec/REC/json-ld/20140116/#reverse-properties)) but [reverse framing](https://w3c.github.io/json-ld-framing/#reverse-framing) is new in 1.1. It's not supported in [our 1.1 work in progress](https://github.com/jsonld-java/jsonld-java/pull/283), but you could check out the titanium-json-ld library, see https://github.com/jsonld-java/jsonld-java/pull/284#issuecomment-653521148.

**Comment by dr0i** [comment]
Closing this.
