### ISSUE TITLE
http://schema.org/ (base URL) does not respond with JSON when 'Accept' header is set

### ISSUE THREAD

**Issue by kevinpeterson** [jsonld-java/jsonld-java#289]
JSON is not returned when setting the 'Accept' header for the URL http://schema.org/.

This can be reproduced here:
`curl -H "Accept:application/ld+json" https://schema.org/ -I`
which returns a response with:
`Content-Type: text/html`

This seems to be just the base URL. Other schema.org URLs return JSON, such as:
`curl -H "Accept:application/ld+json" https://schema.org/docs/jsonldcontext.json -I`

This is causing some tests to fail, such as:
`com.github.jsonldjava.core.DocumentLoaderTest#loadDocumentSchemaOrg`

**Comment by hsolbrig** [comment]
See: https://github.com/RDFLib/rdflib-jsonld/issues/85#issuecomment-632248259

**Comment by danbri** [comment]
@kevinpeterson did you find a workaround?

**Comment by sushrutb** [comment]
I am trying to find a work around to the situation. I am considering use of jarcache.json, and adding all schema.org contexts directly into the classpath. I was wondering if anyone has had any success doing this. Or if you have sample file with just one context, then I can extend that to include all other contexts recursively and publish them here for other people to use.

**Comment by bhoeferlin** [comment]
@sushrutb any progress/success on this topic?

**Comment by sushrutb** [comment]
We basically have abandoned use of jsonld-java and are now using jsoup to parse the dom and extract relevant information to us. As we do not need most recent schema.org ontologies, and are only interested in small subset of information, it was much easier for us to just migrate our code. I am still keep to see this issue resolved and happy to contribute, but based on very cursory reading of the code, I am not sure if I can provide a patch.

**Comment by dr0i** [comment]
WIth #292 I propose an implementation of [following the alternate document location](https://www.w3.org/TR/json-ld11/#alternate-document-location).
