### ISSUE TITLE
0.13.1 causes error with InternetDomainName  of Guava

### ISSUE THREAD

**Issue by ggrasso** [jsonld-java/jsonld-java#293]
I updated to 0.13.1 and I noticed an error in my code.
` The computation terminated in error. Stack Trace: 'java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: EXACT`
After some googling it appears similar to this problem [here](https://issues.apache.org/jira/browse/STORM-538)

**Comment by ansell** [comment]
Thanks, I will add that to the shading setup and release again later today. 

If possible, do you have an example of code that causes this issue, as our existing tests don't seem to trigger this issue.

**Comment by ansell** [comment]
Ahhh, now I understand we don't have integration tests on the shaded jar. The current unit tests are on the standard maven classpath before `maven-shade-plugin` runs. That will need someone to get in and setup a new integration test module.
