### ISSUE TITLE
Maintainers

### ISSUE THREAD

**Issue by sgammon** [jsonld-java/jsonld-java#299]
I'm interested in helping :) how can I apply?

**Comment by ansell** [comment]
Hi Sam,

One of the big tasks that needs attention is the JSON-LD-1.1 support which can be reviewed in PR #283 . We currently support JSON-LD-1.0, with a small amount of 1.1 feature support. It may be a useful strategy to look through the failing tests on that branch to identify the missing features and work on each feature individually.

There are also other smaller bugs and features that may be easier to start working on in the issue backlog:

https://github.com/jsonld-java/jsonld-java/issues

When you have some patches ready, I, or one of the others, will review the Pull Requests and do the releases after the Pull Requests are merged.

Eventually, once contributors have a history we will likely give extra permissions. Currently the small overhead of doing releases is still manageable for me so we mostly need code contributions from a maintainer at this point.

Thanks,

Peter

**Comment by dr0i** [comment]
Nothing to do here. Closing.
