### ISSUE TITLE
Circular dependency error when there is no circular dependency

### ISSUE THREAD

**Issue by umbreak** [jsonld-java/jsonld-java#302]
I have the following json:

```json
{
  "@context" : [
    "https://api.jsonbin.io/b/5fd3a68afbb23c2e36a57f98",
    "https://api.jsonbin.io/b/5fd3a667fbb23c2e36a57f89"
  ],
  "a" : "A",
  "b" : "B",
  "c" : "C"
}
```
The dependency graph from the context links is something like this
![Untitled Diagram (2)](https://user-images.githubusercontent.com/1430863/101988278-e46d5c80-3c98-11eb-9ad1-9602ec4fdbb9.png)

As you can see, there is no recursion here, just the following situaion:
```
root -> https://api.jsonbin.io/b/5fd3a68afbb23c2e36a57f98 -> https://api.jsonbin.io/b/5fd3a637fbb23c2e36a57f79
root -> https://api.jsonbin.io/b/5fd3a667fbb23c2e36a57f89 -> https://api.jsonbin.io/b/5fd3a637fbb23c2e36a57f79
```
 two following contexts pointing to the same final context. However I get the following when trying to expand this document:

```
recursive context inclusion: https://api.jsonbin.io/b/5fd39f4cfbb23c2e36a57cb8
```

That example works in the [playground](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%5B%22https%3A%2F%2Fapi.jsonbin.io%2Fb%2F5fd3a68afbb23c2e36a57f98%22%2C%22https%3A%2F%2Fapi.jsonbin.io%2Fb%2F5fd3a667fbb23c2e36a57f89%22%5D%2C%22a%22%3A%22A%22%2C%22b%22%3A%22B%22%2C%22c%22%3A%22C%22%7D).

I can see the problem comes from the following [line](https://github.com/jsonld-java/jsonld-java/blob/master/core/src/main/java/com/github/jsonldjava/core/Context.java#L193)

**Comment by umbreak** [comment]
According to the [JSON-LD 1.1 implementation](https://www.w3.org/TR/json-ld11-api/#context-processing-algorithms) point 5.2.4, I understand that basically if a remoteContext has already been visited, we can ignore a new visit...so something like
```java

**Comment by dr0i** [comment]
Many thx @umbreak for the report and the solution!
