### ISSUE TITLE
JsonLdError: recursive context inclusion

### ISSUE THREAD

**Issue by naturzukunft** [jsonld-java/jsonld-java#308]
Hi there,
i'm using rdf4j and i think they are using jsonld-java to as parser.
I connetced to pleroma a activitypub server and tried to parse a outbox response.

And the parser throws an `...java.core.JsonLdError: recursive context inclusion: https://www.w3.org/ns/activitystreams`

I issued a bug there: https://git.pleroma.social/pleroma/pleroma/-/issues/2540

But the answer is: 
"So I'd suggest filling a bug to your JSON-LD library instead."

I am curious about the discussion

Fredy

**Comment by bobeal** [comment]
Hi,

Could it be the same as https://github.com/jsonld-java/jsonld-java/pull/303 (merged but not yet part of a new release of the lib)?

**Comment by naturzukunft** [comment]
maybe yes. do you know, when the next release will be? And do you know, if a new release is "immediately" added to rdf4j ?

**Comment by bobeal** [comment]
It seems a 0.13.3 is in preparation: https://github.com/jsonld-java/jsonld-java/commits/release-v0.13.3

No more information on my side, I'm just a tourist (and a basic user of the lib) here :)

**Comment by dr0i** [comment]
@naturzukunft it's indeed likely that this issue is fixed with #303 as @bobeal noted. And  also, yes, a release is on its way. We will let you know when it's published.

**Comment by dr0i** [comment]
From https://git.pleroma.social/pleroma/pleroma/-/issues/2540#note_84526 : 

> .... i updatet to the newest version (few days old) of my parser and now it works. It wasn't a Pleroma bug.

Closing.
