### ISSUE TITLE
loading remote context failed: http://schema.org/

### ISSUE THREAD

**Issue by nicolapaganotti1** [jsonld-java/jsonld-java#325]
Hi,
I have read problem https://github.com/jsonld-java/jsonld-java/issues/180

My json-id
{
  "@context": "https://schema.org",
  "@id": "https://www.fondazioneeinaudi.it/library?id=fed209eb-b616-421d-8850-9387e01d9900",
  "@type": "Book",
  "name": "Acciaio per l'industrializzazione : contributi allo studio del problema siderurgico italiano",
  "author": {
    "@type": "Person",
    "@id": "http://viaf.org/viaf/64048745",
    "name": "Franco Bonelli"},
  "publisher": {
    "@type": "Organization",
    "name": "Fondazione Luigi Einaudi onlus",
    "@id": "http://viaf.org/viaf/132070792",
    "location": "Torino"},
  "datePublished": "1982",
  "isbn": "9788806054526",
  "bookFormat": "EPUB",
  "inLanguage": "it",
  "isPartOf": "Studi",
  "about": "Industria siderurgica - Italia - 1936-1943 - Saggi"
}

This is the code I used
public void toJson(String pathFileBook){
	System.out.println(pathFileBook);
	
	// Open a valid json(-ld) input file
	InputStream inputStream = null;
	try {
		inputStream = new FileInputStream(pathFileBook);
	} catch (FileNotFoundException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
	// Read the file into an Object (The type of this object will be a List, Map, String, Boolean,
	// Number or null depending on the root object in the file).
	Object jsonObject = null;
	
	try {
		jsonObject = JsonUtils.fromInputStream(inputStream);
	} catch (IOException e) {
		// TODO Auto-generated catch block
		System.out.println("secondo errore");
		e.printStackTrace();
	}
	// Create a context JSON map containing prefixes and definitions
	Map context = new HashMap();
	// Customise context...
	// Create an instance of JsonLdOptions with the standard JSON-LD options
	JsonLdOptions options = new JsonLdOptions();
	// Customise options...
	// Call whichever JSONLD function you want! (e.g. compact)
	Object compact = JsonLdProcessor.compact(jsonObject, context, options);
	// Print out the result (or don't, it's your call!)

	try {
		System.out.println(JsonUtils.toPrettyString(compact));
	} catch (IOException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
}

I get a message: loading remote context failed: https://schema.org
I don't understand what I'm missing.
Can you help me please? I use this lib for a university project course.

**Comment by dr0i** [comment]
Hi @nicolapaganotti1, are you using the current build? I tried your json and code and it works fine.

**Comment by nicolapaganotti1** [comment]
Good evening, I have change

          <dependency>
              <groupId>com.github.jsonld-java</groupId>
              <artifactId>jsonld-java</artifactId>
              <version>0.13.0</version>
          </dependency>
         
          Into
          
          <dependency>
              <groupId>com.github.jsonld-java</groupId>
              <artifactId>jsonld-java</artifactId>
              <version>0.13.4</version>
          </dependency>

I received a cordial and quick response from you. Thank you very much. :)

**Comment by nicolapaganotti1** [comment]
Why do all keys in json-ld are replaced with @content key "http://schema.org/" like this
            
             "http://schema.org/about" : "Industria siderurgica - Italia - 1936-1943 - Saggi",

instead of

             "about" : "Industria siderurgica - Italia - 1936-1943 - Saggi"

How can avoid "http://schema.org/" substitution?

Sorry for my english

**Comment by dr0i** [comment]
@nicolapaganotti1 if you've discovered a new issue, please open a new issue.
